### ISSUE TITLE
Data presentation ready

### ISSUE THREAD

**Issue by davedorr9** [data2health/maturity-model#10]

**Comment by ezampino** [comment]
@davedorr9 was this presentation made? Can I close ticket?

**Comment by davedorr9** [comment]
sure, I guess

David Dorr, MD, MS, FACMI
Chief Research Information Officer, OHSU
Professor & Vice Chair, Medical Informatics; Professor, General Internal Medicine & Geriatrics, OHSU
PI, Care Management Plus
The mission of Care Management Plus is to better understand how data, information, and knowledge can assist in transforming health for our most vulnerable populations.
“We are too far out on the Yerkes-Dodson Curve<https://en.wikipedia.org/wiki/Yerkes%E2%80%93Dodson_law> and we need to back off,” – Stuart Slavin
e: dorrd@ohsu.edu<mailto:dorrd@ohsu.edu> v: 503-418-2387 w: http://www.ohsu.edu/cmp
