### ISSUE TITLE
Request IRB determination

### ISSUE THREAD

**Issue by cgcook** [data2health/maturity-model#18]
Note: use this form [Request for Determination (3.15.2018).docx](https://github.com/data2health/maturity-model/files/3075377/Request.for.Determination.3.15.2018.docx)

**Comment by cgcook** [comment]
Hi Liz, can we check in about this task?  I'm curious if this will need to be done at UW, too?

**Comment by kristiholmes** [comment]
is there a common IRB that can be leveraged?
