### ISSUE TITLE
Maturity Model guidebook

### ISSUE THREAD

**Issue by ezampino** [data2health/maturity-model#27]
A collection of MM based upon feedback from the iDTF meeting. Working document can be found [here](https://docs.google.com/document/d/1oJA4dYfaDNRynBG1cOKp-670snA9oDvL0GlSYmBjbhY/edit#heading=h.huhu2i7ucub2)

**Comment by mellybelly** [comment]
@ezampino this is terrific! Perhaps it could be moved to the guidebook? 
https://reusable-data-best-practices.readthedocs.io/en/latest/

**Comment by ezampino** [comment]
@ramussa to complete (by 9/17) assessment of iDTF 'new models' found on "iDTF Requested Models" tab found [here](https://docs.google.com/spreadsheets/d/1o4bii7ZNejqR6ofQ84GXFYKmGv3Y500h4flZxxlsaVM/edit#gid=1115292097)

**Comment by mellybelly** [comment]
@ramussa can you please move the guidegook info on the google doc to the Guidebook read-the-docs platform? Let us know if you need help.
