### ISSUE TITLE
Pilot Tool to limited users

### ISSUE THREAD

**Issue by ezampino** [data2health/maturity-model#33]
Assess the UI, access, etc. with limited number of users in the UW family.

**Comment by ezampino** [comment]
- [ ] Create CRIO List for outreach

- [ ] Pilot to internal CD2H CTSA hubs

**Comment by ezampino** [comment]
Pilot to folks on the 9/27 meeting; participants from survey

**Comment by ezampino** [comment]
Invite list: names in bold came to the 9/24 chat.
Teresa Bosler
**Daniel Robins** 
**Tamara Winden**
Michael Lin
**Firas Wehbe**
Boyd Knosp
Nitin Parikh
Bernie LaSalle
Michael Kahn
**Jeremy Harper**
Justin Starren
**Eugene Sadhu
Tricia Francis
Umberto Tachinardi**
Joseph Finkelstein
Jack Chang
**Christopher Chute
David Dorr
Justin Prosser**
Tim Carey
**Andrew Williams
Peter Elkin**
Bradley Taylor
Sam Volchenboum
Andrey Rzhetsky
Ammar Chaudhry
Michael Bales
**Catherine Craven**
Randy Grout
**Chris Amos**
Steve Patterson
**Nick Anderson**
Genevieve Melton-Meaux
Sean Mooney
**Soumitra Sengupta**
Karthik Natarajan
Jyoti Pathak
Mike Hogarth
Perry Shipman
**Jim Cimino**
Albert Lai
James Campbell 
Scott Campbell 
Ashok Madgapalli 
**Jim McClay
Ali Torkamani**
Chinh Dang
**Bill Barnett
Peter Embi**

**Comment by ezampino** [comment]
Do we want to create logins or have folks pilot as 'guests'?

**Comment by mellybelly** [comment]
@ezampino - few quick things - (1) it would be great to have the internal CD2H team (especially SC/admin core) review before this goes out to community, especially our new engagement and communication director Andrea. (2) for logins, perhaps @eichmann can help with single-sign on- it would be terrific if we can keep all CD2H tools functioning the same in that regard.

**Comment by abwilcox** [comment]
Thanks for the suggestion @mellybelly. We'll work that out with @amvolz and @eichmann. I agree with the goal of making all CD2H tools functioning with the same login if reasonably possible.

**Comment by amvolz** [comment]
Thanks @abwilcox, @mellybelly, @ezampino, @eichmann! I will be developing some SOPs in January for community engagement with debut of new tools. Please feel free to send me ideas!
