### ISSUE TITLE
Deploy version 1 of survey app on production server

### ISSUE THREAD

**Issue by ndobb** [data2health/maturity-model#45]
The Maturity Model Survey app uses a pretty straightforward 3-tier deployment with
1. A React web client application
2. A Python-Flask REST API on the server
3. A REDCap project as a database

We need to deploy 1 & 2 on an RIT server. At a high level this should include:
1. Reserving a subdomain (perhaps https://maturitymodel.rit.uw.edu? let's discuss)
2. Setting up Apache to serve the React client on `/`
3. Setting up Apache to have the Python API listen on `/api/`

Note that we don't need to do anything setting up REDCap, and the React client has its own login page to prevent unauthorized web traffic from getting in. As users from many sites will be using the tool, it *should not* be protected by UW NetID.

**Comment by eichmann** [comment]
@ndobb, as a CD2H project, this should have a cd2h.org domain name (e.g., maturitymodel.cd2h.org).  If you provide me the IP address, I can define the virtual host.

**Comment by ndobb** [comment]
@eichmann Thanks, that makes sense and is fine with me. This is a temporary setup on a short deadline though in order to have it demo-able early next week. 

@jprosser, I'll leave it to you as to how you'd like to proceed on this. Thoughts?

**Comment by eichmann** [comment]
@ndobb configuring the vhost entry is just a few minutes quality time with GoDaddy...  Easily done this weekend.

**Comment by jprosser** [comment]
I can configure Apache to handle that name, that's fine if you'd like to proceed, @eichmann, with creating a cname to staging3.rit.uw.edu but we only run with SSL though.

**Comment by ndobb** [comment]
@eichmann can you let us know if you have the info you need, and when the virtual host is in place? I think maturitymodel.cd2h.org would be great until we hear otherwise.

**Comment by eichmann** [comment]
@ndobb maturitymodel.cd2h.org is live.  I've a wildcard certificate for the whole cd2h.org domain.  Is that satisfactory?  NIH preferred a specific cert for competitions.cd2h.org in the NIH cloud.
