### ISSUE TITLE
Dissemination to participants

### ISSUE THREAD

**Issue by davedorr9** [data2health/maturity-model#8]

**Comment by jmcmurry** [comment]
If you haven't already, please make sure to reach out to the PIs that already expressed interest in the project. Select your project from the dropdown [here](https://docs.google.com/spreadsheets/d/1PR6jLSz3KedD9bEWQcFr-LJRQfkXo_GcFOHXZMOgd7o/edit#gid=0).

**Comment by davedorr9** [comment]
this doesn’t work for me – it is locked down to change the drop-down

David Dorr, MD, MS, FACMI
Chief Research Information Officer, OHSU
Professor & Vice Chair, Medical Informatics; Professor, General Internal Medicine & Geriatrics, OHSU
PI, Care Management Plus
The mission of Care Management Plus is to better understand how data, information, and knowledge can assist in transforming health for our most vulnerable populations.
“We are too far out on the Yerkes-Dodson Curve<https://en.wikipedia.org/wiki/Yerkes%E2%80%93Dodson_law> and we need to back off,” – Stuart Slavin
e: dorrd@ohsu.edu<mailto:dorrd@ohsu.edu> v: 503-418-2387 w: http://www.ohsu.edu/cmp

**Comment by jmcmurry** [comment]
ps. This just in: a coordinated email will be going out for all projects; stay tuned.

**Comment by jmcmurry** [comment]
Baseline email was sent; all ok to proceed with project - specific communications.

**Comment by ezampino** [comment]
This was done at the community chat that took place the end of Sept
