### ISSUE TITLE
Results page - number of participants needs to be accurate

### ISSUE THREAD

**Issue by ezampino** [data2health/maturity-model#90]
Can you please add count of how many people have taken the survey on the results screen?
![Screen Shot 2021-01-25 at 12 16 55 PM](https://user-images.githubusercontent.com/47399796/105761696-48c24380-5f08-11eb-8d12-39b92da7b9cf.png)

**Comment by ezampino** [comment]
The number of people that have taken a particular survey needs to be corrected and incorporated into the results.

**Comment by mh2727** [comment]
completed.
